server:
  port: 8080

spring:
  application:
    name: likeLion

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: jdbc:mysql://localhost:3306/likelion?serverTimezone=Asia/Seoul  # 예: jdbc:mysql://localhost:3306/likelion
    username: root  # 예: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true

  jwt:
    secret: GvF$9aL2!vRxzP3kTnUyBw#qHsE7jDpZ
    expiration: 83400000

  # s3 관련설정 추가 버킷이름, 받은 access-key , secret-key 세팅 리전 ap-northest-2(서울) 로 지정
  # 리전은 AWS 데이터 센터가 위치한 물리적인 지역을 의미
cloud:
  aws:
    s3:
      bucket-name: likelion-session-01
    credentials:
      access-key: ${AWS_ACCESS_KEY}    # 환경 변수로 설정
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
       auto: false